version: "1.0"

services:
  tavern_keeper_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=tavern_keeper_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5442:5432"

volumes:
  db:
